language: node_js

node_js:
  - node
  - 5
  - 4
  - 0.12
  - 0.10

after_script:
  - npm run test
  - codeclimate-test-reporter < lcov.info

addons:
  code_climate:
    repo_token: ENV['REPO_TOKEN']
